### ISSUE TITLE
ProgressHud appearing under RaisedButton

### ISSUE THREAD

**Issue by sohayb** [CosmicMind/MaterialKit#101]
Whenever I try to show progressHud (i.e: MBProgressHUD) it shows under the raised button, I know it's not an issue with your library but do you have any idea of how can that be fixed? 
See screenshot below
![simulator screen shot dec 19 2015 4 33 05 pm](https://cloud.githubusercontent.com/assets/2195533/11913504/6b6ffa7e-a66e-11e5-829b-279d30191108.png)

**Comment by sohayb** [comment]
Fixed that with the following:
````
            let hud = MBProgressHUD.showHUDAddedTo(self.view, animated: true)
            hud.layer.zPosition = 2;
            raisedButton.layer.zPosition = 1;
````

**Comment by danieldahan** [comment]
For the raisedButton, you don't need to use the .layer.zPosition property. You can do raisedButotn.zPosition :) Great that you fixed it.
