### ISSUE TITLE
Alert view

### ISSUE THREAD

**Issue by paulvanwieren** [CosmicMind/MaterialKit#104]
What would be the best way to make a card-like alert view? Should I subclass CardView? 

![components_dialogs_content1](https://cloud.githubusercontent.com/assets/4444436/11915757/12ad8e1e-a66a-11e5-9c0a-cd8408abdac6.png)

**Comment by danieldahan** [comment]
In general subclassing MaterialKit components is not necessary. The easiest way would be to use a CardView and set the appropriate properties. Something like this: 

let cardView: CardView = CardView()
cardView.titleLabel = UILabel()
cardView.titleLabel!.text = "Use Google's location service?"
// ... add styling

cardView.detailLabel = UILabel()
cardView.detailLabel!.text = "Let Google help ... running."
// ... add styling

// make flat buttons (disagree, agree)
cardView.rightButton = [disagree, agree]

When you do the positioning, MaterialLayout would make this easy. 

When you do the depth, probably looking for .Depth5
cardView.shadowDepth = .Depth5

**Comment by danieldahan** [comment]
If you have any further questions, feel free to re-open or create a new ticket :)

**Comment by paulvanwieren** [comment]
How do I actually turn this cardview into an alert? Do I make a UILaertVieeController and set its view to the cardview?

**Comment by paulvanwieren** [comment]
Here's my current UIAlertController code:

```swift
        let alert = UIAlertController(title: title, message: message, preferredStyle: .Alert)
        let action = UIAlertAction(title: "Dismiss", style: .Default, handler: nil)
        alert.addAction(action)
        presentViewController(alert, animated: true, completion: nil)
```

**Comment by danieldahan** [comment]
I haven’t played with what you are trying to do enough to have an accurate answer. Are you required to use an AlertView?

---------------------------------------
Daniel Dahan
 
M: +1 647.627.0770
Skype: djondahan

**Comment by sohayb** [comment]
Was going to open such a ticket. As you know, alerts are required in almost every app (logout prompts, single choice or multiple choice lists and so on) so it's great if you guys have that in mind

**Comment by danieldahan** [comment]
I will put it in upcoming :)
