### ISSUE TITLE
NavigationBarView not working properly

### ISSUE THREAD

**Issue by tengis** [CosmicMind/MaterialKit#105]
Hi, i'm trying to use NavigationBarView on UITableViewController. But somehow it looks like this
<img width="375" alt="screen shot 2015-12-21 at 2 02 46 pm" src="https://cloud.githubusercontent.com/assets/358442/11922508/a04ae62c-a7eb-11e5-83e9-e9a952b643b3.png">

**Comment by danieldahan** [comment]
Hi @tengis Would you be able to share the code you are using to setup the NavigationBarView?

**Comment by tengis** [comment]
@danieldahan Wow that was quick  :+1: 

       let navigationBarView: NavigationBarView = NavigationBarView()
        
        // Stylize.
        navigationBarView.backgroundColor = MaterialColor.indigo.darken1
        
        // To lighten the status bar add the "View controller-based status bar appearance = NO"
        // to your info.plist file and set the following property.
        navigationBarView.statusBarStyle = .LightContent
        
        // Title label.
        let titleLabel: UILabel = UILabel()
        titleLabel.text = "MaterialKit"
        titleLabel.textAlignment = .Left
        titleLabel.textColor = MaterialColor.white
        titleLabel.font = RobotoFont.regularWithSize(20)
        navigationBarView.titleLabel = titleLabel
        navigationBarView.titleLabelInsetsRef.left = 64
        
        // Detail label
        let detailLabel: UILabel = UILabel()
        detailLabel.text = "Build Beautiful Software"
        detailLabel.textAlignment = .Left
        detailLabel.textColor = MaterialColor.white
        detailLabel.font = RobotoFont.regularWithSize(12)
        navigationBarView.detailLabel = detailLabel
        navigationBarView.detailLabelInsetsRef.left = 64
        
        // Menu button.
        let img1: UIImage? = UIImage(named: "ic_menu_white")
        let btn1: FlatButton = FlatButton()
        btn1.pulseColor = MaterialColor.white
        btn1.pulseFill = true
        btn1.pulseScale = false
        btn1.setImage(img1, forState: .Normal)
        btn1.setImage(img1, forState: .Highlighted)
        
        // Star button.
        let img2: UIImage? = UIImage(named: "ic_star_white")
        let btn2: FlatButton = FlatButton()
        btn2.pulseColor = MaterialColor.white
        btn2.pulseFill = true
        btn2.pulseScale = false
        btn2.setImage(img2, forState: .Normal)
        btn2.setImage(img2, forState: .Highlighted)
        
        // Search button.
        let img3: UIImage? = UIImage(named: "ic_search_white")
        let btn3: FlatButton = FlatButton()
        btn3.pulseColor = MaterialColor.white
        btn3.pulseFill = true
        btn3.pulseScale = false
        btn3.setImage(img3, forState: .Normal)
        btn3.setImage(img3, forState: .Highlighted)
        
        // Add buttons to left side.
        navigationBarView.leftButtons = [btn1]
        
        // Add buttons to right side.
        navigationBarView.rightButtons = [btn2, btn3]
        
        // To support orientation changes, use MaterialLayout.
        view.addSubview(navigationBarView)
        navigationBarView.translatesAutoresizingMaskIntoConstraints = false
        MaterialLayout.alignFromTop(view, child: navigationBarView)
        MaterialLayout.alignToParentHorizontally(view, child: navigationBarView)
        MaterialLayout.height(view, child: navigationBarView, height: 70)

**Comment by tengis** [comment]
i tried add this line under the MaterialLayout.height function 

MaterialLayout.width(view, child: navigationBarView, width: view.frame.width)

but still looks bit wrong also after rotate screen still same as first comment

<img width="375" alt="screen shot 2015-12-21 at 2 10 52 pm" src="https://cloud.githubusercontent.com/assets/358442/11922666/d971f48a-a7ec-11e5-8fb6-f3ec0fdf72e3.png">

**Comment by danieldahan** [comment]
The MaterialLayout.width line would conflict with the MaterialLayout.alignToParentHorizontally(view, child: navigationBarView) line.

It looks like you are using the code directly from the example. 

Hmmm... nothing screams issue here. When are you calling this setup code? Also, are you using the latest? 1.25.8?

**Comment by tengis** [comment]
yes i'm using latest version. pod 'MK', '~> 1.25.8'

**Comment by danieldahan** [comment]
Can you remove all code after this line view.addSubview(navigationBarView). 

That should size the NavigationBarView to your screen width x 70 px. I think you want to support rotation, so we wont use this solution in the end, but I want to see that it draws correctly and we are eliminating variables.

**Comment by tengis** [comment]
yeah without those lines working properly

<img width="377" alt="screen shot 2015-12-21 at 2 31 34 pm" src="https://cloud.githubusercontent.com/assets/358442/11922896/b2a07680-a7ef-11e5-920c-d2ec36464edd.png">

**Comment by danieldahan** [comment]
That is good. If you want to support rotation, you will want the previous lines there. What those lines are basically saying is stretch to the parent view horizontally and set the height to 70. This then leads to the TableViewController's view bounds. Is the tableview being spread across the screen width completely?

**Comment by tengis** [comment]
yes. so after that now my navbar moving when i scroll the page

**Comment by danieldahan** [comment]
Sorry, I don't fully understand what you meant. When you scroll the TableViewController the navbar is moving with it? Did you set the MaterialLayout values back? Is the "yes" for my previous question that you confirmed the TableViewController is set to the width of the screen's dimensions?

**Comment by danieldahan** [comment]
If you would like, you can send a sample project over to support@cosmicmind.io and I will take a look, rather than the back and forth questions. If that is easier.

**Comment by tengis** [comment]
Sorry. i didn't add those lines back. moving like this. https://www.dropbox.com/s/8n8jptq1ucaau40/screenshot.mov?dl=0

**Comment by danieldahan** [comment]
I would have to see what is going on. My immediate suggestion is to use a normal ViewController and set the NavigationBarView as a child of that view, then add a tableView to that controller as well.

**Comment by tengis** [comment]
okay. i see. thanks for your quick response it was great help :+1:

**Comment by danieldahan** [comment]
Anytime :)
