### ISSUE TITLE
More components to implement

### ISSUE THREAD

**Issue by sohayb** [CosmicMind/MaterialKit#106]
Can you add more components to you roadmap like SnackBar and Switch?
Thank you

**Comment by danieldahan** [comment]
Yeah, do you want to list some that you think would be nice to add within the next month?

**Comment by sohayb** [comment]
There's many libraries that are trying to port Material Design to iOS, I'm excited about yours because it's fully in swift and for the level of support we get mainly :)
So it would be awesome if this library turned out to be a one stop shop for all material controls!
Here's the components that it would be awesome to add to complete the library, in my opinion this is the importance order:
- SearchBarView
- SearchBarViewController
- TabView
- TabViewController
- Dialogs (regular, single choice, multiple choice)
- Snackbar
- ProgressBar (circular and horizontal)
- DatePicker
- TimePicker
So whatever can fit into your month would be awesome! Feeling a bit optimistic here :)

**Comment by danieldahan** [comment]
Great suggestions. We have a few additions to that internally that we have already prototyped, so let's aim to make this library that one stop shop :). Why we don't just launch so many components is to ensure that the quality of the rollout is high. So far we are happy with the feedback. We also don't just want to be components. We want to help in the journey when building applications, so we are looking to build solid foundations that will grow. 

Thank you for your support.

**Comment by danieldahan** [comment]
@adamdahan Take a look at the list :)

**Comment by sohayb** [comment]
Updated list with ````TextView```` addition

**Comment by danieldahan** [comment]
Yes, how did we forget that one :)

**Comment by adamdahan** [comment]
@sohayb @danieldahan list looks great :+1: I would add the UISwitchControl & Floating Menu too

**Comment by danieldahan** [comment]
Closing this, as the list is updated.

**Comment by zgosalvez** [comment]
@sohayb When you say Snackbar, does that include Toasts?
