### ISSUE TITLE
navigationBarView.statusBarStyle = .LightContent not working

### ISSUE THREAD

**Issue by sohayb** [CosmicMind/MaterialKit#107]
When having ````SideNavigationViewController```` as the windows root controller ````navigationBarView.statusBarStyle = .LightContent```` is not working, what I had to do is to override that class and implement the following to make it work:
````
import UIKit
import MK

class TMSideNavigationViewController: SideNavigationViewController {
    
    override func viewDidLoad() {
        super.viewDidLoad()
        self.setNeedsStatusBarAppearanceUpdate()
        //        self.navigationController?.navigationBar.barStyle = UIBarStyle.Black
    }
    
    override func preferredStatusBarStyle() -> UIStatusBarStyle {
        return .LightContent
    }
    
    override func prefersStatusBarHidden() -> Bool {
        return false
    }
    
}
````
please note that I have "View controller-based status bar appearance" set to "YES" in the plist

**Comment by danieldahan** [comment]
Hi @sohayb, you should set the "View controller-based status bar appearance" to "NO"

Let me know :)

**Comment by sohayb** [comment]
Yeah that worked! Apparently, "YES" is the default as well, because I didn't set it at first.
Thanks a lot!

**Comment by HowardCsie** [comment]
Same problem.But i don't get you :(

**Comment by danieldahan** [comment]
You have to set the value in the info.plist file.
