### ISSUE TITLE
How to implement selection in SideNavigationViewController?

### ISSUE THREAD

**Issue by vishiswoz** [CosmicMind/MaterialKit#108]
Hi, I'm trying to implement your example of a SideNavigationViewController. I set the MainViewController and the SideViewController in the storyboard. The SideViewController is a TableView with 2 items in the list. How can I implement selection so when I click on one of the items in the list I transition to a new ViewController?

**Comment by adamdahan** [comment]
@vishiswoz That would be a good place to implement the delegation pattern. We don't make any assumptions as to what you will put in the SideViewController so you will have to implement that yourself. 

Example tip:

protocol SomeViewControllerDelegate { 
       func didSelectRowAtIndexPath(indexPath: NSIndexPath)
} 

// in your subclass of UIViewController
var delegate: SomeViewControllerDelegate?

// in your didSelectRowAtIndexPath where your UITableViewDelegate resides

delegate?.didSelectRowAtIndexPath(indexPath)  // where indexPath is that of your table view delegates didSelectRowAtIndexPath method.

Hope that helps!

**Comment by adamdahan** [comment]
@vishiswoz closing this ticket but feel free to keep commenting on it if you need more support.

**Comment by danieldahan** [comment]
@vishiswoz To clarify, are you meaning that when you click on a button, that the mainViewController transitions to a new one?

**Comment by vishiswoz** [comment]
Thanks for the help! I was able to implement it.
