### ISSUE TITLE
CardView not being placed in front of all subviews

### ISSUE THREAD

**Issue by vishiswoz** [CosmicMind/MaterialKit#109]
I have a cardView that I'm using as sort of an alert and I called 
``` 
let cardView: CardView = CardView()
...
self.view.bringSubviewToFront(cardView)
```
However, the card view is still being blocked by FlatButtons, although I don't know why. I have two FlatButtons that are overlapping my cardview, even though the cardview is supposed to be in front of all of the subviews.

**Comment by sohayb** [comment]
I face a similar problem with ````MBProgressHUD````, I solved it with the following:
````
                let hud = MBProgressHUD.showHUDAddedTo(self.view, animated: true)
                hud.layer.zPosition = 2
                self.flatButton.zPosition = 1
````
So I guess you can do the same with your ````CardView```` in place of the HUD

**Comment by vishiswoz** [comment]
It worked thanks!

**Comment by sohayb** [comment]
Awesome! can you please close the issue?

**Comment by adamdahan** [comment]
@sohayb thanks!
