### ISSUE TITLE
Which minimum ios version is required to support in order to use it ?

### ISSUE THREAD

**Issue by indrajitsinh** [CosmicMind/MaterialKit#110]
i am using Xcode 6.2 
can i able to use it ?
does it compitible with ios 7 or ios 8 or ios 8+ ??

**Comment by sohayb** [comment]
You need minimum iOS 8.0 (as defined in the podspec) and XCode 7 with Swift 2.0

**Comment by danieldahan** [comment]
Thank you @sohayb :)
