### ISSUE TITLE
Going to previous viewController in UINavigationController

### ISSUE THREAD

**Issue by sohayb** [CosmicMind/MaterialKit#111]
When going to an internal viewController I wanted to disable the side menu so what I did is the following:
````
    override func viewWillAppear(animated: Bool) {
        super.viewWillAppear(animated)
        sideNavigationViewController?.enabled = false
    }
````
But this didn't bring back the default gesture to go to previous controller using the pan gesture.
Any idea on how I can bring that to work again? Because from what I saw that you're setting  ````userInteractionEnabled```` to false when doing that.

**Comment by danieldahan** [comment]
Try using the enabled property of the side nav.

So in your view controller, use

sideNavigationViewController?.enabled = false 

---------------------------------------
Daniel Dahan
 
M: +1 647.627.0770
Skype: djondahan

**Comment by sohayb** [comment]
This is what I'm doing, or am I missing something?

**Comment by danieldahan** [comment]
Sorry, I didn't see your code, I was on my phone. I am going to make an adjustment that may help you. I will be pushing it today with some other pushes.

**Comment by sohayb** [comment]
Awesome. Thanks! :)

**Comment by danieldahan** [comment]
So the userInteractionEnabled is set to false when the sideNav is opened. This stops any engagement with the mainViewController. I added some code to remove and add the gestures appropriately when setting the enabled property. It is in the development branch. Let me know how that works for you. If there is any further issue, please re-open the ticket or create a new one :)

**Comment by sohayb** [comment]
Unfortunately that didn't work :/ (Couldn't reopen the ticket)

**Comment by danieldahan** [comment]
Do you mind emailing support@cosmicmind.io with a sample project of what you are doing?

**Comment by sohayb** [comment]
Will do, thank you.

**Comment by danieldahan** [comment]
Hey, @sohayb 

In the MainViewController, you have a line: 

 self.navigationController?.setNavigationBarHidden(true, animated: false)

under it, add this line: 

navigationController?.interactivePopGestureRecognizer?.delegate = nil.

Please test this, and if it works as desired, close the ticket. Thank you!

**Comment by sohayb** [comment]
Well that worked! Had to use another library to get around that.
Thanks a lot :+1:

**Comment by danieldahan** [comment]
Another library?

For which part?

---------------------------------------
Daniel Dahan
 
M: +1 647.627.0770
Skype: djondahan

**Comment by sohayb** [comment]
to get the swipe gesture working, it adds the swipe gesture manually to controllers (back port it to iOS 6, imagine that :P)

**Comment by danieldahan** [comment]
lol, crazy. Well, best of luck! 

---------------------------------------
Daniel Dahan
 
M: +1 647.627.0770
Skype: djondahan

**Comment by sohayb** [comment]
Well I removed it now thanks to your solution :)
