### ISSUE TITLE
Title label appearing on top of Navigation bar buttons

### ISSUE THREAD

**Issue by sohayb** [CosmicMind/MaterialKit#112]
When the title is big enough, the title labels appears on top of the top buttons, I think that the title label width in the ````NavigationBarView```` should be calculated based on the buttons width.
<img width="373" alt="screen shot 2016-01-02 at 6 12 58 pm" src="https://cloud.githubusercontent.com/assets/2195533/12075084/cd0df4ac-b17c-11e5-944b-f9dbedbc2f34.png">

**Comment by sohayb** [comment]
Well I solved it like this:
````
navigationBarView.titleLabelInsetsRef.right = 192
````
But that brings me to another issue I wanted to discuss since forever, I think the ````NavigationBarView```` takes so much code to get initialised. I guess having ````@IBDesignable```` can solve part of the issue, what do you guys think?

**Comment by danieldahan** [comment]
Agreed, I will make that adjustment today with the SearchBarView I am working on :)

**Comment by sohayb** [comment]
That's some great news!!! :+1:

**Comment by danieldahan** [comment]
I thought you would like that :)

---------------------------------------
Daniel Dahan
 
M: +1 647.627.0770
Skype: djondahan

**Comment by danieldahan** [comment]
@sohayb So this isn't actually a bug, it was part of the design. It was left to the developer to manage this. In the next release, the SearchBarView and NavigationBarView will handle the sizing as suggested. 

Thank you!
