### ISSUE TITLE
Onboarding

### ISSUE THREAD

**Issue by chaitanya-ramji** [CosmicMind/MaterialKit#113]
A possible feature in the next few updates could be onboard screens. I am working on one myself but couldn't get the same UI/UX as Google does in all of it's apps. For eg: Background color transitioning along with the UIPageControl transition.

**Comment by danieldahan** [comment]
Yeah, I like that idea. I'll leave this up for the next couple days as I think about how that could work.

**Comment by danieldahan** [comment]
Hey, I am going to close this issue, as we are planning to add onboarding shortly. All the best and thank you for the suggestion!
