### ISSUE TITLE
License restrictions

### ISSUE THREAD

**Issue by tskulbru** [CosmicMind/MaterialKit#115]
This library uses AGPL license. Because of this any app which uses this license needs to make its source code available (open source). 

I feel that this is bad, and not really thought through. Whats the reasoning behind this? Why not use a more permissive license such as [MIT](http://opensource.org/licenses/mit-license.php)?

 As it stands now, as long as I'm not just playing around I can't really use this awesome library. I was thinking of adding features to this library, but as long as its AGPL it's not really something I feel is worth my time.

[More information about the differences between them](http://programmers.stackexchange.com/questions/150534/want-to-use-a-lib-for-my-project-confused-with-license-agpl-vs-mit-license)

**Comment by sohayb** [comment]
Oops! This poses a problem for me as well, I didn't pay attention to that earlier.. @danieldahan what do you this?

**Comment by danieldahan** [comment]
It was originally put under AGPL, because I wasn't sure what would happen with this library. I will have a conclusion later today as to what I plan on doing.

**Comment by tskulbru** [comment]
It basically makes it impossible for any non-free app to use the library unless they want to give their source-code to anyone who asks for it. Thats bad.

>The AGPL is based on the GPL, not the LGPL. It does not contain any linking exceptions, and any work using AGPL code (linked or otherwise, modified or not) must also be AGPL licensed and distributed.

>Using separate processes can circumvent the (A)GPL, but this is murky ground. If your end application depends on the external process, such that it wouldn't function properly without it, then it would be considered a derived work of the AGPL software.

>In most cases where people use separate GPL applications in closed source programs, they provide the GPL work as an optional extension, or an alternative back-end to some other piece of code etc.

>The (A)GPL work cannot be distributed alongside the final application even as a separate app (eg, putting them into the same archive or repository), although it's fine to provide instructions on where to find the GPL work and how to use it with your app.

> [Answer for "AGPL What you can do and what you can't"](http://programmers.stackexchange.com/a/107931/30003)

**Comment by danieldahan** [comment]
Yes, I know. As mentioned, I didn't know what I was going to do and this framework blew up. So I am evaluating other licenses right now.

**Comment by danieldahan** [comment]
My projects will go under the BSD license :) Give me a second.

**Comment by danieldahan** [comment]
1.27.9 should do the trick :) Enjoy!
