### ISSUE TITLE
Setting the placement of TextField's titleLabel

### ISSUE THREAD

**Issue by vishiswoz** [CosmicMind/MaterialKit#120]
I noticed that you changed the placement of the TextField's titleLabel so that's a little higher above the TextField compared to before. Is it possible to have a method so that way I can set the placement to what I want it? I feel that the current placement of the titleLabel is a little too high and I want to lower it a little bit.

**Comment by danieldahan** [comment]
Hey, yes. There is a property you can set that will adjust the distance for you. For example:

textField.titleLabelAnimationDistance = 4
