### ISSUE TITLE
Any plans on having a tabBar?

### ISSUE THREAD

**Issue by tiagopigatto** [CosmicMind/MaterialKit#121]
Are there any plans to implement a tabBar like this? ![image](https://camo.githubusercontent.com/3d1ce6c5a1399350b0eff3cea4832d5fabcb363a/68747470733a2f2f646c2e64726f70626f7875736572636f6e74656e742e636f6d2f752f38303830323430302f4d6174657269616c44657369676e2f4d4454616242617256696577436f6e74726f6c6c65722e676966?)

That's the only issue I didn't migrate to this awesome framework yet :(

**Comment by danieldahan** [comment]
Yes, there are plans. We are working on many new features and that is one of them :)

I'd say start playing with MaterialKit if you like its direction, so when the updates come, you are ready at full speed. 

The new features focus a lot on navigation and transitions. 

:)

**Comment by tiagopigatto** [comment]
Do you have any dates? :))

**Comment by danieldahan** [comment]
The new features will start rolling out in February. Exact dates, not sure.
