### ISSUE TITLE
Unable to run examples due to MaterialKit.framework not being linked

### ISSUE THREAD

**Issue by jspenc72** [CosmicMind/MaterialKit#122]
1. Cloned the repo
2. open Examples
3. Select either programmatic or storyboard project
4. Build/Run on Emulator
5. Results in the following error "No such module 'MaterialKit'

<img width="1400" alt="cardviewerror" src="https://cloud.githubusercontent.com/assets/2913536/12472378/a8778fc6-bfc4-11e5-9f2a-bdb9ec91213c.png">

**Comment by jspenc72** [comment]
After compiling the MaterialKit target I am able to run however I am getting an error saying that the images are not found.

**Comment by danieldahan** [comment]
You have to embed the MaterialKit.framework in the project you want to run.

For example:

1. Click on the MaterialView project in the examples directory
2. Click on the general tab
3. Compile the MaterialKit framework against the Generic Device, or actual device in the schemes dropdown
4. embed the MaterialKit.framework in the project
5. run the project

**Comment by jspenc72** [comment]
Should the framework already be embedded since the example is a demonstration of the features of that framework?

**Comment by danieldahan** [comment]
That would cause maintenance and linking errors. A framework cannot avoid the setup, which is why organizations like CocoaPods and Carthage have emerged. Either way, this issue is considered solved. Please feel free to reopen or create a new issue if any arise. Thank you!

**Comment by qiaoyan** [comment]
Hi, do you consider include this comment in readme? Take a while to find here.

**Comment by danieldahan** [comment]
Which example are you trying to run? MaterialKit should be Material. The MaterialKit name is an old name for the framework and was most likely left in accidentally in that example.

**Comment by qiaoyan** [comment]
Hi, I mean the following steps generally, not specific of framework name.
By the way, when I download sourcecode, the first step is change the link path of Material framework project.
![screen shot 2016-02-02 at 10 41 54 am](https://cloud.githubusercontent.com/assets/1080270/12738415/786605fc-c99b-11e5-9428-dfb0bf7a9d36.png)
Great project, thanks.


--------

    Click on the MaterialView project in the examples directory
    Click on the general tab
    Compile the MaterialKit framework against the Generic Device, or actual device in the schemes dropdown
    embed the MaterialKit.framework in the project
    run the project

**Comment by danieldahan** [comment]
Try now, I made an update to the project settings. Let me know :)

---------------------------------------
Daniel Dahan
 
M: +1 647.627.0770
Skype: djondahan
