### ISSUE TITLE
SideNavigationViewController example

### ISSUE THREAD

**Issue by WooD1k** [CosmicMind/MaterialKit#74]
Hello!

May you please create a simple sample project that uses SideNavigationViewController?
I'm trying to use it, but can't understand how should it work :)

I event can't use it as is explained at repo README.md
Just getting a black screen, but according to the storyboard this screen should be white and should contain 'touch me' button

I've created a sample project, so you will be able to 'reproduce' my failure :)

Here is the link to my repo with the sample - [SideNavigationViewControllerTest](https://github.com/WooD1k/SideNavigationViewControllerTest/)
Please let me know if i may provide some additional information.
Thanks in advance!

**Comment by adamdahan** [comment]
Hi @WooD1k, 

There are a few issues with your approach: 

When creating an iOS project you have three choices 
1. Using a template 
2. Start with an empty project and add a storyboard or xib. 
3. Pure code no storyboards

Based on your sample project SideNavigationViewControllerTest it seems you started the project with either 1 or 2 from the choices above. 

The first issue to your approach was this piece of code: 

window = UIWindow(frame: UIScreen.mainScreen().bounds)
window!.rootViewController = SideNavigationViewController(mainViewController: ViewController(), sideViewController: SideMenuViewController())
        window!.makeKeyAndVisible()

Click on the Blue project file and then click on the app name under "Targets"... Look at the "Deployment Info" you will see that you have "Main" set under "Main Interface" 

In order for your appDidFinishLaunchingWithOptions code to run properly you will need to make sure there is no file specified under "Main Interface" in the deployment info section of your apps target. 

Hope that helps!

:)

**Comment by WooD1k** [comment]
Hello @adamdahan 

Many thanks for your detailed answer!

I've added a new view controller for object panel, changed class to SideNavigationViewController and there is no any properties at outlets sections(main or side), here is the screenshots:

<img width="1524" alt="main storyboard edited 2015-11-30 12-25-00" src="https://cloud.githubusercontent.com/assets/1052325/11469238/a221ea70-975d-11e5-84cd-bec4b7847b47.png">
<img width="1552" alt="main storyboard edited 2015-11-30 12-27-19" src="https://cloud.githubusercontent.com/assets/1052325/11469263/c9adb1fa-975d-11e5-8cf8-323e7f0e4f4b.png">

Thanks in advance!

**Comment by adamdahan** [comment]
Hey @WooD1k, 

I see the issue now. There is no IBOutlet property for the mainViewController. We don't use storyboards much ourselves but we will definitely make that available in a future update. 

To remedy your situation for the time being until the next release: 

Click on the Blue project file and then click on the app name under "Targets"... Look at the "Deployment Info" and delete the file "Main" set for the "Main Interface" and do it programmatically. 

Just replace the identifiers below-> 

let storyboard = UIStoryboard(name: "Main", bundle: nil)
let mainVC = storyboard.instantiateViewControllerWithIdentifier("YourViewControllerIdentifier")
let sideVC = storyboard.instantiateViewControllerWithIdentifier("YourSideViewControllerIdentifier")
window = UIWindow(frame: UIScreen.mainScreen().bounds)
window?.rootViewController = SideNavigationViewController(mainViewController: mainVC, sideViewController: sideVC)
window?.makeKeyAndVisible()

Hope that helps and we will push support for storyboards in the next update!

**Comment by adamdahan** [comment]
@WooD1k you can track the storyboard support ticket here: https://github.com/CosmicMind/MaterialKit/issues/75

**Comment by WooD1k** [comment]
@adamdahan many thanks!

**Comment by adamdahan** [comment]
@WooD1k my pleasure. 

And just a side note: The above fix allows you to keep doing your work in storyboards. The only programmatic thing done is passing the rootViewController to your apps window. So basically you don't need to do the dragging in IB to hook up the SideNavigationViewController. Just do that part programmatically and use the storyboards as you wish for the individual view controllers in your app. 

:)
