### ISSUE TITLE
Text Fields & Form Components

### ISSUE THREAD

**Issue by jovincroninwilesmith** [CosmicMind/MaterialKit#78]
Implement texts fields from the material design guideline. Would help it be a more well rounded material library

**Comment by danieldahan** [comment]
@jovincroninwilesmith fully agree :) The upcoming week has some additional updates. If the text field does not get in by the end of this week, it will be in the following week.

**Comment by jovincroninwilesmith** [comment]
Awesome! You rule! 

We are scoping out material libraries for our application and It would be amazing to use your's and not have to bring in multiple libraries :+1:

**Comment by danieldahan** [comment]
Sweet :) We are glad that we have support as we have a wonderful roadmap being put together to build a great framework :) I am going to leave this ticket open to track the progression of your feature request.

**Comment by danieldahan** [comment]
Moving this to the upcoming RoadMap, and closing for now. Thank you!
