### ISSUE TITLE
How to switch out mainViewController in SideNavigationViewController

### ISSUE THREAD

**Issue by rockwotj** [CosmicMind/MaterialKit#80]
How can you change out the mainViewController in the SideNavigationViewController? Right now I reassign the mainViewController to a new one, but the UI seems frozen after that. Do I need to recall `prepareView()` or `prepareMainView()` however, they are both private right now. 

Or do you just suggest trading out the SideNavigationViewController from the window?

**Comment by rockwotj** [comment]
Nevermind, I think the following did it for me:

```swift
func switchToViewController(controller : UIViewController) {
        SideNavigationViewControl.mainViewController.willMoveToParentViewController(nil)
        SideNavigationViewControl.mainViewController.removeFromParentViewController()
        SideNavigationViewControl.mainViewController = controller
        controller.view.frame = SideNavigationViewControl.view.bounds
        SideNavigationViewControl.addChildViewController(controller)
        SideNavigationViewControl.view.addSubview(controller.view)
        controller.didMoveToParentViewController(SideNavigationViewControl)
    }
```

**Comment by danieldahan** [comment]
Good question. The initial design of the SideNavigation was to be simple, so we didn't include a swapping mechanism. There are two solutions that you can immediately use, and soon we will add support for your question.

1. You can do what you suggested and swap out the SideNavigationController. 
2. You can place a base UIViewController as the mainViewController and internally swap child UIViewControllers as you see fit, this has benefits in general over a direct swap, such as centralizing logic etc... 

I do believe there is a need to have support for swapping out UIViewControllers internally within SideViewController, so we can leave this ticket open and we will add support for it.

**Comment by danieldahan** [comment]
@rockwotj Nice solution, we will look at this issue further and make a smoother process for swapping. Thanks for reaching out. I will close this ticket now, and put the feature within our internal roadmap. Thanks!

**Comment by danieldahan** [comment]
@adamdahan Let's plan this in for our next release with a swap with animation effect.

**Comment by danieldahan** [comment]
Moving the issue to the upcoming RoadMap, and closing for now. Thank you!

**Comment by HowardCsie** [comment]
Hello.Is now there a easy way to switch different rootViewController ?

**Comment by danieldahan** [comment]
Use the SideNavigationController `transitionFromRootViewController` method.

**Comment by HowardCsie** [comment]
`let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let mainTVC =  storyboard.instantiateViewControllerWithIdentifier("MainTVC") as! MainTVC
        let navigationController: NavigationController = AppNavigationController(rootViewController: mainTVC)
        window = UIWindow(frame: UIScreen.mainScreen().bounds)
        window?.rootViewController = SideNavigationController(rootViewController: navigationController, leftViewController: AppLeftViewController())
        window?.makeKeyAndVisible()`
This is my setting.
I want to put `sideNavigationController?.transitionFromRootViewController()` in leftViewController,but how to switch back the original rootViewController instead of declaring a new one?

**Comment by danieldahan** [comment]
If you want to support the backButton, then you need to use a NavigationController as your rootViewController in the SideNavigationController. The option is also to use a NavigationController in the AppLeftViewController to support the backButton there as well.
