### ISSUE TITLE
SideNavigationController : IOS 9 Depreciation

### ISSUE THREAD

**Issue by wm-j-ray** [CosmicMind/MaterialKit#82]
setStatusBarHidden depreciated, use ViewController.prefersStatusBarHidden instead, but how should this be applied in this instance?

Thanx

@line 452 

    	private func toggleStatusBar(hide: Bool = false) {
		if hideStatusBar {
			if isViewBasedAppearance {
				UIApplication.sharedApplication().setStatusBarHidden(hide, withAnimation: .Slide)
			} else {
				dispatch_async(dispatch_get_main_queue(), {
					if let w = UIApplication.sharedApplication().keyWindow {
						w.windowLevel = hide ? UIWindowLevelStatusBar + 1 : 0
					}
				})
			}
		}
	}

**Comment by danieldahan** [comment]
We are making some really nice updates today, and this issue will be one of them. I'll have a better idea of the overall resolution shortly.

**Comment by danieldahan** [comment]
Try the latest release 1.24.9. The warning should no longer come up. If you may confirm this, I will close the ticket. Thank you :)

**Comment by danieldahan** [comment]
I confirmed this is no longer an issue in 1.24.10. If it persists, please reopen the issue. Thank you!
