### ISSUE TITLE
SideNavigationMenu freezing

### ISSUE THREAD

**Issue by rockwotj** [CosmicMind/MaterialKit#83]
I recently make the fix from #80 to switch out the mainViewController, however after a few swaps, the side nav view becomes unresponsive. After that I cannot receive any clicking in the side nav, any ideas what's happening?

**Comment by adamdahan** [comment]
@rockwotj any sample code you can send? That would be great so we can to help you with a fix until we roll out support for the centre view controller swapping (next release).

**Comment by rockwotj** [comment]
@adamdahan, thanks for your quick response, when is that next release scheduled? (JW)

I have this in app delegate.
```swift
func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {
        window = UIWindow(frame: UIScreen.mainScreen().bounds)
        rootNavViewController = SideNavigationViewController(
            mainViewController: ExampleController(),
            sideViewController: SideMenuViewController()
        )
        window!.rootViewController = rootNavViewController
        window!.makeKeyAndVisible()
        return true
    }
    
    func switchToViewController(controller : UIViewController) {
        rootNavViewController.mainViewController.willMoveToParentViewController(nil)
        rootNavViewController.mainViewController.removeFromParentViewController()
        rootNavViewController.mainViewController = controller
        controller.view.frame = rootNavViewController.view.bounds
        rootNavViewController.addChildViewController(controller)
        rootNavViewController.view.addSubview(controller.view)
        controller.didMoveToParentViewController(rootNavViewController)
    }
```

and then in the `SideMenuViewController`, when an item is clicked, I call  `switchToViewController` like so

```swift
appDelegate.rootNavViewController.close()
appDelegate.switchToViewController(AnotherExampleViewController()!)
```

So after clicking this a couple times and navigating around, the side bar freezes. 

Any ideas? If not I can wait until your official support and release.

**Comment by danieldahan** [comment]
@rockwotj Monday is the next release. Also for your issue, my suggestion would be to use a base mainViewController and within their swap child UIViewControllers.

**Comment by danieldahan** [comment]
@rockwotj Were you able to get this working? let me know if you need further assistance by re-opening the ticket and sharing your code :)

**Comment by rockwotj** [comment]
@danieldahan I wasn't able too, I was just planning on waiting until monday :smiley:

**Comment by danieldahan** [comment]
Ah okay :) I didn't want to hold you up for that issue. Basically where your solution was having an issue, is that internally there are some properties and such that need to be updated and you wouldn't have access from the external API. A supported solution will be ready for Monday. All the best.

**Comment by danieldahan** [comment]
@rockwotj Hey, we added the mainViewController swap in release 1.24.13. Let us know if there are any issues. There is an example in the Examples Programmatic directory.

**Comment by rockwotj** [comment]
Awesome! That fixes everything, thanks! The transition is a very nice touch. 

However, if you're using the SideNav to change controllers (See below) and close the drawer at the same time, the side nav hangs and glitches a bit, which I'm assuming is coming from trying execute both animations at once?

```swift
let appDelegate = UIApplication.sharedApplication().delegate as! AppDelegate
        var viewController : UIViewController?
        switch (indexPath.row) {
        case 0:
            viewController = NewUIViewController()
        default:
            viewController = nil
        }
        if viewController != nil {
            appDelegate.rootSideNav.mainViewController = viewController;
        }
        appDelegate.rootSideNav.close()
```

**Comment by rockwotj** [comment]
This helped prevent the jumpy animations.
```swift
        let appDelegate = UIApplication.sharedApplication().delegate as! AppDelegate
        var viewController : MaterialController?
        switch (indexPath.row) {
        case 0:
            viewController = PublisherListViewController()
        default:
            viewController = nil
        }
        if viewController != nil {
            appDelegate.rootSideNav.mainViewController = viewController;
        }
        dispatch_async(dispatch_get_main_queue()) {
            appDelegate.rootSideNav.close()
        }
```

**Comment by danieldahan** [comment]
Cool :) I will look into this. Also, so you know, if you are in a viewController, you do not need to get the appDelegate for a reference. There is a UIViewController extension that allows you to access the SideNav. 

sideNavigationViewController?.close() 

would work. 

---------------------------------------
Daniel Dahan
 
M: +1 647.627.0770
Skype: djondahan

**Comment by danieldahan** [comment]
@rockwotj Major update for you. I added a transitionFromMainViewController function that allows you to specify the animation transition you would like and a completion block at the end where you should call the close method to avoid any blocking animations. This can be found in 1.24.15.

**Comment by rockwotj** [comment]
Perfect, just what I needed. Thank you so much for your quick work!
