### ISSUE TITLE
One sample project

### ISSUE THREAD

**Issue by sohayb** [CosmicMind/MaterialKit#84]
Hello,
I was trying to view all the features of the library with all the attached samples, so I took the liberty of creation a sample project that demonstrates all the library samples (Using StoryBoards). I use CocoaPods. here's the project link https://github.com/sohayb/MaterialKitSamples
Thanks for the library btw :+1:

**Comment by danieldahan** [comment]
@sohayb Looks great :) and thank you. I am leaving this open so others may see it.

**Comment by adamdahan** [comment]
@sohayb awesome :) :+1:

**Comment by sohayb** [comment]
I will add the I need to add the programmatic way of creating the views to the sample, will update after you add the new components (Wednesday as you promised :) )

**Comment by danieldahan** [comment]
@sohayb Wonderful :)

**Comment by paulvanwieren** [comment]
Should close this issue

**Comment by sohayb** [comment]
This issue is kept open because, as @danieldahan stated, so others may see it.
The samples repo will be updated as soon as the search text field is released.

**Comment by sohayb** [comment]
Project updated with programmatic samples now

**Comment by danieldahan** [comment]
@sohayb Thank you
@paulvanwieren Generally leaving an issue open is not what I like to do. In this case though, until we have more resources for others to learn, I believe this is beneficial. In the future, we plan on having a community driven site that will allow people to share the wonderful things they are doing with MaterialKit. This project would be a great place for that.

**Comment by danieldahan** [comment]
@sohayb I am going to close this now.

The reason I am closing this, is that there was a large update and more to come, and this project will no longer reflect a complete example. If you would like, you are always welcome to open a new ticket with examples and such. 

Thank you! :)
