### ISSUE TITLE
Add textField to NavigationBarView

### ISSUE THREAD

**Issue by sohayb** [CosmicMind/MaterialKit#86]
Is there any plan to add a text field (for search functionality) in the NavigationBarView in the coming days? I'm in the middle of developing an app that uses that, and if NavigationBarView then I should look for another component 😞

**Comment by danieldahan** [comment]
@sohayb Yes, there is. We have new components coming out, TextField and SearchBarView are  amongst them. Our roadmap will be up shortly. If you have any further questions, please re-open or create a new issue :)

**Comment by sohayb** [comment]
Awesome!!! May I ask when will that come out? :)

**Comment by danieldahan** [comment]
I am anticipating by Wednesday if not sooner. This upcoming week there will be a bunch of releases to help support the growth of MaterialKit :)

**Comment by sohayb** [comment]
Thanks a lot :+1:
