### ISSUE TITLE
Title label isn't centred vertically in NavigationBarView

### ISSUE THREAD

**Issue by sohayb** [CosmicMind/MaterialKit#88]
When there's no detail label, the title label isn't centred vertically in the nav bar view

**Comment by danieldahan** [comment]
Good morning :) I will reproduce this and have a solution for you.

**Comment by sohayb** [comment]
I really appreciate the hard work you're putting into this library :+1: , I'm on the other side of the world so good evening :)

**Comment by danieldahan** [comment]
Hi @sohayb May you send me the code you are using to setup the NavigationBarView? Also, are you using Storyboards, or doing this fully programmatically?

**Comment by danieldahan** [comment]
@sohayb Building MaterialKit with the community is wonderful :) We appreciate it :)

**Comment by sohayb** [comment]
I'm sorry, I won't be able to send you anything today as I'm head over heals in some other stuff. Regarding the setup, I'm adding the NavigationBarView in the storyboard but the setup is in the code.
I'm going to abuse your library really hard, so you'll always get my feedback :)

**Comment by danieldahan** [comment]
lol, please use it in every shape and form :) Cool, send me a sample of code when you get the chance. 

---------------------------------------
Daniel Dahan
 
M: +1 647.627.0770
Skype: djondahan

**Comment by danieldahan** [comment]
@sohayb Any chance on posting the code? Thank you :)

**Comment by sohayb** [comment]
Something was off in my code, sorry about that!
Closing this now
