### ISSUE TITLE
FlatButton image

### ISSUE THREAD

**Issue by paulvanwieren** [CosmicMind/MaterialKit#89]
After setting the FlatButton image, the image is being shrunk on my iPhone (shows up fine in the storyboard).

**Comment by danieldahan** [comment]
Would you be able to share the code you are using to setup the FlatButton?

**Comment by paulvanwieren** [comment]
I think I can reproduce it properly now. It appears to happen only when you are using an icon that's larger than the button. The system UIButton scales the image down for you if you use an image that's larger than the button, but FlatButton appears to not be doing that down-scaling correctly. I think this is a feature add/enhancement. Will close. 

![screen shot 2015-12-17 at 2 23 50 am](https://cloud.githubusercontent.com/assets/4444436/11867332/55f8ee72-a465-11e5-8276-b78f5be07082.png)

![img_1128](https://cloud.githubusercontent.com/assets/4444436/11867339/613316f0-a465-11e5-9823-13080e233bec.PNG)
