### ISSUE TITLE
MaterialKit.xcworkspace should be reorganized

### ISSUE THREAD

**Issue by dobaduc** [CosmicMind/MaterialKit#91]
First of all thanks a lot for your great work!

I've just tried out this framework today and noticed about a little inconvenience: the MaterialKit framework is now being linked to the examples using the absolute path (Something like `/Users/danieldahan/Library/Developer/Xcode/DerivedData/MaterialKit-xxxxxxxxx`). With current configuration there will be some extra steps required to make the examples testable.

Any idea to improve this?

**Comment by danieldahan** [comment]
Hi @dobaduc Yes, I have fixed it in development. The issue was part in the gitignore and in leaving the file linked in the project. Our next release is targeted for today, which will resolve this issue.
