### ISSUE TITLE
[Idea] IBDesignable and IBInspectable support

### ISSUE THREAD

**Issue by dobaduc** [CosmicMind/MaterialKit#92]
Hi,
Is there any plan to support `@IBDesignable` and `@IBInspectable` for current component? Does everyone think it's nice to have by the way?

Here is a quick experiment with some enum properties updated to be inspectable on the interface builder:

![Experiment](https://cloud.githubusercontent.com/assets/746055/11837573/1f745ef8-a425-11e5-8998-7649a4634619.png)

**Comment by danieldahan** [comment]
Yes, I agree and this is in the plan. With everyone requesting it, it will be included very soon :) Shortly we will have a roadmap posted, and the details of when that will be released will be available.

**Comment by dobaduc** [comment]
Cool, looking forward to it!
