### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by paulvanwieren** [CosmicMind/MaterialKit#94]
In all of my projects, I'm getting this warning. What can I do to correct it?

![screen shot 2015-12-17 at 1 36 07 am](https://cloud.githubusercontent.com/assets/4444436/11866246/a9742f32-a45e-11e5-9bdf-0393e865c456.png)

**Comment by danieldahan** [comment]
Yes, this is known. In the next update it will be removed. :) I will close this ticket once the fix has been pushed.

**Comment by danieldahan** [comment]
This should be fixed in 1.25.2 :)
