### ISSUE TITLE
SideNavigationViewController PanGesture

### ISSUE THREAD

**Issue by reeichert** [CosmicMind/MaterialKit#95]
Hi, i have a questio.

From my mainviewcontroller, i use "self.navigationController.pushViewController" to get to another view
but the default panGesture to back to my mainviewcontroller, is replaced by pangesture of sideNavigation. Even if i try presentViewController or ShowViewController, i keep getting pangesture of sideNavigation.. 

there is any way of remove this gesture of some viewcontroller??

thanks

**Comment by danieldahan** [comment]
Hi, @reeichert 

Yes, in any viewController, you can set the sideNavigationViewController.enabled property to false. 

sideNavigationViewController?.enabled = false

That will disable the SideNavigationViewController :)

Let me know if that works for you.

**Comment by danieldahan** [comment]
Hi there, I am going to close this, and if you have any further issues, please re-open or make a new issue. Thank you!
