### ISSUE TITLE
What's the suggested way to show list of cards?

### ISSUE THREAD

**Issue by horaceho** [CosmicMind/MaterialKit#97]
How about a tutorial of how to use CardView in UITableView or UICollectionView? For example, is it simple as putting CardView in a UITableViewCell's contentView?

**Comment by danieldahan** [comment]
Yes pretty much. CardView is like any other UIView when it comes to adding it as a child in the view hierarchy. Depending on your usage you would decide on a CollectionView or TableView. That said, the only issue you would face is the sizing of the CardView within the CollectionViewCell or TableViewCell, which depends on how you set your views up. 

There are more examples coming that would clearly highlight this. When the SearchBarView is added, there will be an example with a dynamic list to show the results. That example will use a view like CardView within the cells of the list. 

I am going to close this issue, if you have any further questions, please re-open the issue or make a new one :)
