### ISSUE TITLE
Button icon not found

### ISSUE THREAD

**Issue by horaceho** [CosmicMind/MaterialKit#98]
When I try to add a FabButton:
````
let addButton: FabButton = FabButton()
let icon: UIImage? = UIImage(named: "ic_create_white")
addButton.setImage(icon, forState: .Normal)
addButton.setImage(icon, forState: .Highlighted)
addButton.addTarget(self, action: "handleAddButton", forControlEvents: .TouchUpInside)
````
the button shows up OK but the icon is missing. Changing the second line to:
````
let icon: UIImage = UIImage(named: "ic_create_white")!
````
gives a _fatal error: unexpectedly found nil while unwrapping an Optional value_

I installed MK via Cocoapods:
````
platform :ios, "8.0"
use_frameworks!

pod 'MK'
````
 Am I missing somethiing?

**Comment by danieldahan** [comment]
Yes, you are missing the image itself. You can find that here https://design.google.com/icons/. I am closing this issue, if you need any further help, please re-open or create a new ticket. :)
